name: meshexam
description: "MeshExam Mobile - Decentralized Offline Examination System"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  nearby_connections: ^3.1.2
  flutter_blue_plus: ^1.16.2
  graphview: ^1.2.0
  crypto: ^3.0.3
  uuid: ^4.3.3
  intl: ^0.19.0
  pdf: ^3.10.8
  printing: ^5.11.1
  path_provider: ^2.1.2
  share_plus: ^7.2.2
  cupertino_icons: ^1.0.6
  flutter_animate: ^4.5.2
  kiosk_mode: ^0.8.0
  file_picker: ^8.0.3
  open_filex: ^4.5.0
  camera: ^0.12.0+1
  google_mlkit_face_detection: ^0.13.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: 2.4.7

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/logo.jpeg"
  adaptive_icon_background: "#0F172A"
  adaptive_icon_foreground: "assets/logo.jpeg"

flutter_native_splash:
  color: "#0F172A"
  image: "assets/logo.jpeg"
  android: true
  ios: false

flutter:
  uses-material-design: true
  assets:
    - assets/logo.jpeg
